services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tandt-travel
    ports:
      - "3090:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    restart: unless-stopped
